INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (1, 1, 1, 'amtlee', 'আমতলী', 'আমতলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (2, 1, 1, 'bamna', 'বামনা', 'বামনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (3, 1, 1, 'brguna-sdr', 'বরগুনা সদর', 'বরগুনা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (4, 1, 1, 'betagee', 'বেতাগী', 'বেতাগী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (5, 1, 1, 'pathrghata', 'পাথরঘাটা', 'পাথরঘাটা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (6, 1, 1, 'taltlee', 'তালতলী', 'তালতলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (7, 2, 1, 'agoiljhara', 'আগৈলঝাড়া', 'আগৈলঝাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (8, 2, 1, 'gourndee', 'গৌরনদী', 'গৌরনদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (9, 2, 1, 'banaree-para', 'বানারী পাড়া', 'বানারী পাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (10, 2, 1, 'ujirpur', 'উজিরপুর', 'উজিরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (11, 2, 1, 'muladee', 'মুলাদী', 'মুলাদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (12, 2, 1, 'babugnj', 'বাবুগঞ্জ', 'বাবুগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (13, 2, 1, 'mehendeegnj', 'মেহেন্দীগঞ্জ', 'মেহেন্দীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (14, 2, 1, 'hijla', 'হিজলা', 'হিজলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (15, 2, 1, 'brisal-sdr', 'বরিশাল সদর', 'বরিশাল সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (16, 2, 1, 'bakergnj', 'বাকেরগঞ্জ', 'বাকেরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (17, 3, 1, 'vola-sdr', 'ভোলা সদর', 'ভোলা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (18, 3, 1, 'borhanuddin', 'বোরহানউদ্দিন', 'বোরহানউদ্দিন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (19, 3, 1, 'doult-khan', 'দৌলত খান', 'দৌলত খান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (20, 3, 1, 'lalmohn', 'লালমোহন', 'লালমোহন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (21, 3, 1, 'tjumuddin', 'তজুমুদ্দিন', 'তজুমুদ্দিন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (22, 3, 1, 'cr-fzasn', 'চর ফ্যাশন', 'চর ফ্যাশন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (23, 3, 1, 'mnpura', 'মনপুরা', 'মনপুরা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (24, 4, 1, 'kathaliya', 'কাঠালিয়া', 'কাঠালিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (25, 4, 1, 'rajapur', 'রাজাপুর', 'রাজাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (26, 4, 1, 'jhalkathee-sdr', 'ঝালকাঠী সদর', 'ঝালকাঠী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (27, 4, 1, 'nlchiti', 'নলছিটি', 'নলছিটি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (28, 5, 1, 'mirjagnj', 'মির্জাগঞ্জ', 'মির্জাগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (29, 5, 1, 'ptuyakhalee-sdr', 'পটুয়াখালী সদর', 'পটুয়াখালী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (30, 5, 1, 'dumkee', 'দুমকী', 'দুমকী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (31, 5, 1, 'baufl', 'বাউফল', 'বাউফল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (32, 5, 1, 'dsmina', 'দশমিনা', 'দশমিনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (33, 5, 1, 'glacipa', 'গলাচিপা', 'গলাচিপা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (34, 5, 1, 'klapara', 'কলাপাড়া', 'কলাপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (35, 5, 1, 'rangoabalee', 'রাঙ্গাবালী', 'রাঙ্গাবালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (36, 6, 1, 'pirojpur-sdr', 'পিরোজপুর সদর', 'পিরোজপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (37, 6, 1, 'najirpur', 'নাজিরপুর', 'নাজিরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (38, 6, 1, 'indurkanee', 'ইন্দুরকানী', 'ইন্দুরকানী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (39, 6, 1, 'vandariya', 'ভান্ডারিয়া', 'ভান্ডারিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (40, 6, 1, 'kaukhalee', 'কাউখালী', 'কাউখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (41, 6, 1, 'necharabad', 'নেছারাবাদ', 'নেছারাবাদ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (42, 6, 1, 'mthbareeya', 'মঠবাড়ীয়া', 'মঠবাড়ীয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (43, 7, 2, 'aleekdm', 'আলীকদম', 'আলীকদম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (44, 7, 2, 'bandrban-sdr', 'বান্দরবান সদর', 'বান্দরবান সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (45, 7, 2, 'lama', 'লামা', 'লামা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (46, 7, 2, 'naikshzngchri', 'নাইক্ষ্যংছড়ি', 'নাইক্ষ্যংছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (47, 7, 2, 'royangchri', 'রোয়াংছড়ি', 'রোয়াংছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (48, 7, 2, 'ruma', 'রুমা', 'রুমা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (49, 7, 2, 'thanci', 'থান্‌চি', 'থান্‌চি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (50, 12, 2, 'nasirngr', 'নাসিরনগর', 'নাসিরনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (51, 12, 2, 'srail', 'সরাইল', 'সরাইল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (52, 12, 2, 'asugnj', 'আশুগঞ্জ', 'আশুগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (53, 12, 2, 'brahmnbariya-sdr', 'ব্রাহ্মণবাড়িয়া সদর', 'ব্রাহ্মণবাড়িয়া সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (54, 12, 2, 'bijyngr', 'বিজয়নগর', 'বিজয়নগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (55, 12, 2, 'akhaura', 'আখাউড়া', 'আখাউড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (56, 12, 2, 'ksba', 'কসবা', 'কসবা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (57, 12, 2, 'nbeengr', 'নবীনগর', 'নবীনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (58, 12, 2, 'bancharampur', 'বাঞ্ছারামপুর', 'বাঞ্ছারামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (59, 13, 2, 'kcuya', 'কচুয়া', 'কচুয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (60, 13, 2, 'mtlb-dkshin', 'মতলব দক্ষিণ', 'মতলব দক্ষিণ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (61, 13, 2, 'mtlb-uttr', 'মতলব উত্তর', 'মতলব উত্তর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (62, 13, 2, 'canndpur-sdr', 'চাঁদপুর সদর', 'চাঁদপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (63, 13, 2, 'haimcr', 'হাইমচর', 'হাইমচর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (64, 13, 2, 'fridgnj', 'ফরিদগঞ্জ', 'ফরিদগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (65, 13, 2, 'hajeegnj', 'হাজীগঞ্জ', 'হাজীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (66, 13, 2, 'sahrasti', 'শাহরাস্তি', 'শাহরাস্তি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (67, 14, 2, 'chaglnaya', 'ছাগলনাইয়া', 'ছাগলনাইয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (68, 14, 2, 'fulgajee', 'ফুলগাজী', 'ফুলগাজী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (69, 14, 2, 'prsuram', 'পরশুরাম', 'পরশুরাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (70, 14, 2, 'fenee-sdr', 'ফেনী সদর', 'ফেনী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (71, 14, 2, 'dagnvuunnnga', 'দাগনভূঁঞা', 'দাগনভূঁঞা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (72, 14, 2, 'sonagajee', 'সোনাগাজী', 'সোনাগাজী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (73, 15, 2, 'catkhil', 'চাটখিল', 'চাটখিল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (74, 15, 2, 'sonaimudee', 'সোনাইমুড়ী', 'সোনাইমুড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (75, 15, 2, 'senbag', 'সেনবাগ', 'সেনবাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (76, 15, 2, 'begmgnj', 'বেগমগঞ্জ', 'বেগমগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (77, 15, 2, 'subrncr', 'সুবর্ণচর', 'সুবর্ণচর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (78, 15, 2, 'noyakhalee-sdr', 'নোয়াখালী সদর', 'নোয়াখালী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (79, 15, 2, 'kompaneegnj', 'কোম্পানীগঞ্জ', 'কোম্পানীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (80, 15, 2, 'kbirhat', 'কবিরহাট', 'কবিরহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (81, 15, 2, 'hatiya', 'হাতিয়া', 'হাতিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (82, 16, 2, 'ramgnj', 'রামগঞ্জ', 'রামগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (83, 16, 2, 'lkshneepur-sdr', 'লক্ষ্ণীপুর সদর', 'লক্ষ্ণীপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (84, 16, 2, 'raypur', 'রায়পুর', 'রায়পুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (85, 16, 2, 'kmlngr', 'কমলনগর', 'কমলনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (86, 16, 2, 'ramgtee', 'রামগতী', 'রামগতী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (87, 8, 2, 'meersrai', 'মীরসরাই', 'মীরসরাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (88, 8, 2, 'ftikchri', 'ফটিকছড়ি', 'ফটিকছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (89, 8, 2, 'sndweep', 'সন্দ্বীপ', 'সন্দ্বীপ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (90, 8, 2, 'khulsee', 'খুলশী', 'খুলশী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (91, 8, 2, 'pahartlee', 'পাহাড়তলী', 'পাহাড়তলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (92, 8, 2, 'seetakund', 'সীতাকুন্ড', 'সীতাকুন্ড');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (93, 8, 2, 'raujan', 'রাউজান', 'রাউজান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (94, 8, 2, 'boyalkhalee', 'বোয়ালখালী', 'বোয়ালখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (95, 8, 2, 'rangguneeya', 'রাংগুনীয়া', 'রাংগুনীয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (96, 8, 2, 'ptiya', 'পটিয়া', 'পটিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (97, 8, 2, 'anoyara', 'আনোয়ারা', 'আনোয়ারা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (98, 8, 2, 'krnfulee', 'কর্ণফুলী', 'কর্ণফুলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (99, 8, 2, 'bannskhalee', 'বাঁশখালী', 'বাঁশখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (100, 8, 2, 'satkaniya', 'সাতকানিয়া', 'সাতকানিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (101, 8, 2, 'cndnais', 'চন্দনাইশ', 'চন্দনাইশ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (102, 8, 2, 'lohagara', 'লোহাগাড়া', 'লোহাগাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (103, 8, 2, 'hathajaree', 'হাটহাজারী', 'হাটহাজারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (104, 8, 2, 'bayjid-bostamee', 'বায়জিদ বোস্তামী', 'বায়জিদ বোস্তামী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (105, 8, 2, 'canndgaoo', 'চাঁদগাও', 'চাঁদগাও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (106, 8, 2, 'pannclais', 'পাঁচলাইশ', 'পাঁচলাইশ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (107, 8, 2, 'bakleeya', 'বাকলীয়া', 'বাকলীয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (108, 8, 2, 'dblmuring', 'ডবলমুরিং', 'ডবলমুরিং');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (109, 8, 2, 'kotyalee', 'কোতয়ালী', 'কোতয়ালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (110, 8, 2, 'halishr', 'হালিশহর', 'হালিশহর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (111, 8, 2, 'cttgram-port', 'চট্টগ্রাম পোর্ট', 'চট্টগ্রাম পোর্ট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (112, 8, 2, 'ptengoa', 'পতেঙ্গা', 'পতেঙ্গা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (113, 18, 7, 'atoyaree', 'আটোয়ারী', 'আটোয়ারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (114, 18, 7, 'pncgr-sdr', 'পঞ্চগড় সদর', 'পঞ্চগড় সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (115, 18, 7, 'tenntuliya', 'তেঁতুলিয়া', 'তেঁতুলিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (116, 18, 7, 'boda', 'বোদা', 'বোদা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (117, 18, 7, 'debeegnj', 'দেবীগঞ্জ', 'দেবীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (118, 19, 7, 'thakurgannoo-sdr', 'ঠাকুরগাঁও সদর', 'ঠাকুরগাঁও সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (119, 19, 7, 'raneesngkoil', 'রাণীশংকৈল ', 'রাণীশংকৈল ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (120, 19, 7, 'baliyadanggee', 'বালিয়াডাংগী', 'বালিয়াডাংগী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (121, 19, 7, 'hripur', 'হরিপুর', 'হরিপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (122, 19, 7, 'peergnj', 'পীরগঞ্জ', 'পীরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (123, 20, 7, 'beergnj', 'বীরগঞ্জ', 'বীরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (124, 20, 7, 'kaharol', 'কাহারোল', 'কাহারোল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (125, 20, 7, 'birl', 'বিরল', 'বিরল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (126, 20, 7, 'bocagnj', 'বোচাগঞ্জ', 'বোচাগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (127, 20, 7, 'dinajpur-sdr', 'দিনাজপুর সদর', 'দিনাজপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (128, 20, 7, 'cirirbndr', 'চিরিরবন্দর', 'চিরিরবন্দর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (129, 20, 7, 'khansama', 'খানসামা', 'খানসামা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (130, 20, 7, 'fulbaree', 'ফুলবাড়ী', 'ফুলবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (131, 20, 7, 'parwteepur', 'পার্বতীপুর', 'পার্বতীপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (132, 20, 7, 'birampur', 'বিরামপুর', 'বিরামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (133, 20, 7, 'ghoraghat', 'ঘোড়াঘাট', 'ঘোড়াঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (134, 20, 7, 'hakimpur', 'হাকিমপুর', 'হাকিমপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (135, 20, 7, 'nbabgnj', 'নবাবগঞ্জ', 'নবাবগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (136, 21, 7, 'dimla', 'ডিমলা', 'ডিমলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (137, 21, 7, 'domar', 'ডোমার', 'ডোমার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (138, 21, 7, 'neelphamaree-sdr', 'নীলফামারী সদর', 'নীলফামারী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (139, 21, 7, 'jldhaka', 'জলঢাকা', 'জলঢাকা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (140, 21, 7, 'kisorgnj', 'কিশোরগঞ্জ', 'কিশোরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (141, 21, 7, 'soiydpur', 'সৈয়দপুর', 'সৈয়দপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (142, 22, 7, 'hateebandha', 'হাতীবান্ধা', 'হাতীবান্ধা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (143, 22, 7, 'patgram', 'পাটগ্রাম', 'পাটগ্রাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (144, 22, 7, 'aditmaree', 'আদিতমারী', 'আদিতমারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (145, 22, 7, 'kaleegnj', 'কালীগঞ্জ', 'কালীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (146, 22, 7, 'lalmnirhat-sdr', 'লালমনিরহাট সদর', 'লালমনিরহাট সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (147, 23, 7, 'rngpur-sdr', 'রংপুর সদর', 'রংপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (148, 23, 7, 'gnggacra', 'গংগাচড়া', 'গংগাচড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (149, 23, 7, 'bdrgnj', 'বদরগঞ্জ', 'বদরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (150, 23, 7, 'taragnj', 'তারাগঞ্জ', 'তারাগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (151, 23, 7, 'kauniya', 'কাউনিয়া', 'কাউনিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (152, 23, 7, 'peergacha', 'পীরগাছা', 'পীরগাছা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (153, 23, 7, 'mithapukur', 'মিঠাপুকুর', 'মিঠাপুকুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (154, 23, 7, 'peergnj-2', 'পীরগঞ্জ', 'পীরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (155, 24, 7, 'vurunggamaree', 'ভুরুংগামারী', 'ভুরুংগামারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (156, 24, 7, 'nageswree', 'নাগেশ্বরী', 'নাগেশ্বরী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (157, 24, 7, 'fulbaree-2', 'ফুলবাড়ী', 'ফুলবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (158, 24, 7, 'kurigram-sdr', 'কুড়িগ্রাম সদর', 'কুড়িগ্রাম সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (159, 24, 7, 'rajarhat', 'রাজারহাট', 'রাজারহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (160, 24, 7, 'ulipur', 'উলিপুর', 'উলিপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (161, 24, 7, 'cr-rajibpur', 'চর রাজিবপুর', 'চর রাজিবপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (162, 24, 7, 'cilmaree', 'চিলমারী', 'চিলমারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (163, 24, 7, 'roumaree', 'রৌমারী', 'রৌমারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (164, 25, 7, 'sundrgnj', 'সুন্দরগঞ্জ', 'সুন্দরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (165, 25, 7, 'gaibandha-sdr', 'গাইবান্ধা সদর', 'গাইবান্ধা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (166, 25, 7, 'plasbaree', 'পলাশবাড়ী', 'পলাশবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (167, 25, 7, 'sadullapur', 'সাদুল্লাপুর', 'সাদুল্লাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (168, 25, 7, 'gobindgnj', 'গোবিন্দগঞ্জ', 'গোবিন্দগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (169, 25, 7, 'fulchri', 'ফুলছড়ি', 'ফুলছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (170, 25, 7, 'saghata', 'সাঘাটা', 'সাঘাটা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (171, 26, 6, 'jypurhat-sdr', 'জয়পুরহাট সদর', 'জয়পুরহাট সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (172, 26, 6, 'panncbibi', 'পাঁচবিবি', 'পাঁচবিবি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (173, 26, 6, 'akkelpur', 'আক্কেলপুর', 'আক্কেলপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (174, 26, 6, 'kalai', 'কালাই', 'কালাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (175, 26, 6, 'kshetlal', 'ক্ষেতলাল', 'ক্ষেতলাল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (176, 27, 6, 'sariyakandi', 'সারিয়াকান্দি', 'সারিয়াকান্দি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (177, 27, 6, 'sonatla', 'সোনাতলা', 'সোনাতলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (178, 27, 6, 'sibgnj', 'শিব্গঞ্জ', 'শিব্গঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (179, 27, 6, 'admdighee', 'আদমদিঘী', 'আদমদিঘী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (180, 27, 6, 'dupcannciya', 'দুপচাঁচিয়া', 'দুপচাঁচিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (181, 27, 6, 'kahalu', 'কাহালু', 'কাহালু');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (182, 27, 6, 'nndeegram', 'নন্দীগ্রাম', 'নন্দীগ্রাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (183, 27, 6, 'dhunt', 'ধুনট', 'ধুনট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (184, 27, 6, 'serpur', 'শেরপুর', 'শেরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (185, 27, 6, 'bgura-sdr', 'বগুড়া সদর', 'বগুড়া সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (186, 27, 6, 'gabtlee', 'গাবতলী', 'গাবতলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (187, 27, 6, 'sajahanpur', 'শাজাহানপুর', 'শাজাহানপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (188, 28, 6, 'sibgnj-2', 'শিবগঞ্জ', 'শিবগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (189, 28, 6, 'volahat', 'ভোলাহাট', 'ভোলাহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (190, 28, 6, 'gomstapur', 'গোমস্তাপুর', 'গোমস্তাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (191, 28, 6, 'nacol', 'নাচোল', 'নাচোল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (192, 28, 6, 'cannpainbabgnj-sdr', 'চাঁপাইনবাবগঞ্জ সদর', 'চাঁপাইনবাবগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (193, 29, 6, 'niyamtpur', 'নিয়ামতপুর', 'নিয়ামতপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (194, 29, 6, 'porsa', 'পোরশা', 'পোরশা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (195, 29, 6, 'sapahar', 'সাপাহার', 'সাপাহার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (196, 29, 6, 'dhamirhat', 'ধামইরহাট', 'ধামইরহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (197, 29, 6, 'ptneetla', 'পত্নীতলা', 'পত্নীতলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (198, 29, 6, 'bdlgachee', 'বদলগাছী', 'বদলগাছী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (199, 29, 6, 'mhadebpur', 'মহাদেবপুর', 'মহাদেবপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (200, 29, 6, 'manda', 'মান্দা', 'মান্দা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (201, 29, 6, 'noogann-sdr', 'নওগাঁ সদর', 'নওগাঁ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (202, 29, 6, 'atrai', 'আত্রাই', 'আত্রাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (203, 29, 6, 'raneengr', 'রাণীনগর', 'রাণীনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (204, 30, 6, 'godagaree', 'গোদাগাড়ী', 'গোদাগাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (205, 30, 6, 'tanor', 'তানোর', 'তানোর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (206, 30, 6, 'mohnpur', 'মোহনপুর', 'মোহনপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (207, 30, 6, 'pba', 'পবা', 'পবা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (208, 30, 6, 'bagmara', 'বাগমারা', 'বাগমারা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (209, 30, 6, 'duurgapur', 'দূর্গাপুর', 'দূর্গাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (210, 30, 6, 'puthiya', 'পুঠিয়া', 'পুঠিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (211, 30, 6, 'bagha', 'বাঘা', 'বাঘা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (212, 30, 6, 'carghat', 'চারঘাট', 'চারঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (213, 30, 6, 'boyaliya', 'বোয়ালিয়া', 'বোয়ালিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (214, 30, 6, 'mtihar', 'মতিহার', 'মতিহার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (215, 30, 6, 'rajpara', 'রাজপাড়া', 'রাজপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (216, 30, 6, 'sah-mkhdum', 'শাহ্‌ মখদুম', 'শাহ্‌ মখদুম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (217, 31, 6, 'bagatipara', 'বাগাতিপাড়া', 'বাগাতিপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (218, 31, 6, 'lalpur', 'লালপুর', 'লালপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (219, 31, 6, 'nldangoa', 'নলডাঙ্গা', 'নলডাঙ্গা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (220, 31, 6, 'nator-sdr', 'নাটোর সদর', 'নাটোর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (221, 31, 6, 'singra', 'সিংড়া', 'সিংড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (222, 31, 6, 'braigram', 'বড়াইগ্রাম', 'বড়াইগ্রাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (223, 31, 6, 'gurudaspur', 'গুরুদাসপুর', 'গুরুদাসপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (224, 32, 6, 'sirajgnj-sdr', 'সিরাজগঞ্জ সদর', 'সিরাজগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (225, 32, 6, 'kajeepur', 'কাজীপুর', 'কাজীপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (226, 32, 6, 'kamarkhnd', 'কামারখন্দ', 'কামারখন্দ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (227, 32, 6, 'raygnj', 'রায়গঞ্জ', 'রায়গঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (228, 32, 6, 'taras', 'তাড়াশ', 'তাড়াশ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (229, 32, 6, 'ulla-para', 'উল্লা পাড়া', 'উল্লা পাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (230, 32, 6, 'belkuci', 'বেলকুচি', 'বেলকুচি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (231, 32, 6, 'couhalee', 'চৌহালী', 'চৌহালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (232, 32, 6, 'sahajadpur', 'শাহাজাদপুর', 'শাহাজাদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (233, 33, 6, 'bera', 'বেড়া ', 'বেড়া ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (234, 33, 6, 'sannthiya', 'সাঁথিয়া', 'সাঁথিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (235, 33, 6, 'sujangr', 'সুজানগর', 'সুজানগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (236, 33, 6, 'vanggura', 'ভাংগুড়া', 'ভাংগুড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (237, 33, 6, 'catmohr', 'চাটমোহর', 'চাটমোহর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (238, 33, 6, 'fridpur', 'ফরিদপুর', 'ফরিদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (239, 33, 6, 'atghriya', 'আটঘরিয়া', 'আটঘরিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (240, 33, 6, 'eeswrdee', 'ঈশ্বরদী', 'ঈশ্বরদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (241, 33, 6, 'pabna-sdr', 'পাবনা সদর', 'পাবনা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (242, 34, 4, 'mujibngr', 'মুজিবনগর', 'মুজিবনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (243, 34, 4, 'meherpur-sdr', 'মেহেরপুর সদর', 'মেহেরপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (244, 34, 4, 'gangnee', 'গাংনী', 'গাংনী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (245, 35, 4, 'doultpur', 'দৌলতপুর', 'দৌলতপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (246, 35, 4, 'veramara', 'ভেড়ামারা', 'ভেড়ামারা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (247, 35, 4, 'mirpur', 'মিরপুর', 'মিরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (248, 35, 4, 'kushtiya-sdr', 'কুষ্টিয়া সদর', 'কুষ্টিয়া সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (249, 35, 4, 'khoksa', 'খোকসা', 'খোকসা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (250, 35, 4, 'kumarkhalee', 'কুমারখালী', 'কুমারখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (251, 36, 4, 'cuyadangoa-sdr', 'চুয়াডাঙ্গা সদর', 'চুয়াডাঙ্গা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (252, 36, 4, 'almdangga', 'আলমডাংগা', 'আলমডাংগা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (253, 36, 4, 'damurhuda', 'দামুরহুদা', 'দামুরহুদা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (254, 36, 4, 'jeebn-ngr', 'জীবন নগর', 'জীবন নগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (255, 37, 4, 'soilkupa', 'শৈলকুপা', 'শৈলকুপা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (256, 37, 4, 'hrinakundu', 'হরিনাকুন্ডু', 'হরিনাকুন্ডু');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (257, 37, 4, 'jhinaidh-sdr', 'ঝিনাইদহ সদর', 'ঝিনাইদহ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (258, 37, 4, 'kotcanndpur', 'কোটচাঁদপুর', 'কোটচাঁদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (259, 37, 4, 'mhespur', 'মহেশপুর', 'মহেশপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (260, 37, 4, 'kalignj', 'কালিগঞ্জ', 'কালিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (261, 38, 4, 'sarsa', 'শার্শা', 'শার্শা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (262, 38, 4, 'cougacha', 'চৌগাছা', 'চৌগাছা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (263, 38, 4, 'jhikrgacha', 'ঝিকরগাছা', 'ঝিকরগাছা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (264, 38, 4, 'zsor-sdr', 'যশোর সদর', 'যশোর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (265, 38, 4, 'ovyngr', 'অভয়নগর', 'অভয়নগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (266, 38, 4, 'bagharpara', 'বাঘারপাড়া', 'বাঘারপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (267, 38, 4, 'mnirampur', 'মনিরামপুর', 'মনিরামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (268, 38, 4, 'kesbpur', 'কেশবপুর', 'কেশবপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (269, 39, 4, 'magura-sdr', 'মাগুরা সদর', 'মাগুরা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (270, 39, 4, 'sreepur', 'শ্রীপুর', 'শ্রীপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (271, 39, 4, 'mohammdpur', 'মোহাম্মদপুর', 'মোহাম্মদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (272, 39, 4, 'salikha', 'শালিখা', 'শালিখা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (273, 40, 4, 'nrail-sdr', 'নড়াইল সদর', 'নড়াইল সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (274, 40, 4, 'kaliya', 'কালিয়া', 'কালিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (275, 40, 4, 'lohagra', 'লোহাগড়া', 'লোহাগড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (276, 41, 4, 'citlmaree', 'চিতলমারী', 'চিতলমারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (277, 41, 4, 'fkirhat', 'ফকিরহাট', 'ফকিরহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (278, 41, 4, 'mollahat', 'মোল্লাহাট', 'মোল্লাহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (279, 41, 4, 'bagerhat-sdr', 'বাগেরহাট সদর', 'বাগেরহাট সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (280, 41, 4, 'kcuya-2', 'কচুয়া', 'কচুয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (281, 41, 4, 'mongla', 'মোংলা', 'মোংলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (282, 41, 4, 'rampal', 'রামপাল', 'রামপাল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (283, 41, 4, 'morlgnj', 'মোড়লগঞ্জ', 'মোড়লগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (284, 41, 4, 'srnkhola', 'শরণখোলা', 'শরণখোলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (285, 42, 4, 'btiyaghata', 'বটিয়াঘাটা', 'বটিয়াঘাটা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (286, 42, 4, 'dakop', 'দাকোপ', 'দাকোপ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (287, 42, 4, 'dighliya', 'দিঘলিয়া', 'দিঘলিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (288, 42, 4, 'ruupsa', 'রূপসা', 'রূপসা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (289, 42, 4, 'terkhada', 'তেরখাদা', 'তেরখাদা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (290, 42, 4, 'dumuriya', 'ডুমুরিয়া', 'ডুমুরিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (291, 42, 4, 'fultla', 'ফুলতলা', 'ফুলতলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (292, 42, 4, 'kyra', 'কয়রা', 'কয়রা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (293, 42, 4, 'paikgacha', 'পাইকগাছা', 'পাইকগাছা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (294, 42, 4, 'khulna-sdr', 'খুলনা সদর', 'খুলনা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (295, 42, 4, 'sonadangoa', 'সোনাডাঙ্গা', 'সোনাডাঙ্গা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (296, 42, 4, 'doultpur-2', 'দৌলতপুর', 'দৌলতপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (297, 42, 4, 'khalispur', 'খালিসপুর', 'খালিসপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (298, 42, 4, 'khan-jahan-alee', 'খান জাহান আলী', 'খান জাহান আলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (299, 43, 4, 'klaroya', 'কলারোয়া', 'কলারোয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (300, 43, 4, 'tala', 'তালা', 'তালা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (301, 43, 4, 'satksheera-sdr', 'সাতক্ষীরা সদর', 'সাতক্ষীরা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (302, 43, 4, 'kalignj-2', 'কালিগঞ্জ', 'কালিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (303, 43, 4, 'asasuni', 'আশাশুনি', 'আশাশুনি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (304, 43, 4, 'debhata', 'দেবহাটা', 'দেবহাটা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (305, 43, 4, 'szamngr', 'শ্যামনগর', 'শ্যামনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (306, 44, 3, 'dhnbaree', 'ধনবাড়ী', 'ধনবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (307, 44, 3, 'mdhupur', 'মধুপুর', 'মধুপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (308, 44, 3, 'vuungapur', 'ভূঞাপুর', 'ভূঞাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (309, 44, 3, 'gopalpur', 'গোপালপুর', 'গোপালপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (310, 44, 3, 'ghatail', 'ঘাটাইল', 'ঘাটাইল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (311, 44, 3, 'kalihatee', 'কালিহাতী', 'কালিহাতী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (312, 44, 3, 'tangoail-sdr', 'টাঙ্গাইল সদর', 'টাঙ্গাইল সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (313, 44, 3, 'delduyar', 'দেলদুয়ার', 'দেলদুয়ার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (314, 44, 3, 'nagrpur', 'নাগরপুর', 'নাগরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (315, 44, 3, 'mirjapur', 'মির্জাপুর', 'মির্জাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (316, 44, 3, 'basail', 'বাসাইল', 'বাসাইল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (317, 44, 3, 'skhipur', 'সখিপুর', 'সখিপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (318, 45, 5, 'bkshignj', 'বকশিগঞ্জ', 'বকশিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (319, 45, 5, 'dewangnj', 'দেওয়ানগঞ্জ', 'দেওয়ানগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (320, 45, 5, 'islampur', 'ইসলামপুর', 'ইসলামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (321, 45, 5, 'madargnj', 'মাদারগঞ্জ', 'মাদারগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (322, 45, 5, 'melandh', 'মেলান্দহ', 'মেলান্দহ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (323, 45, 5, 'srishabaree', 'সরিষাবাড়ী', 'সরিষাবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (324, 45, 5, 'jamalpur-sdr', 'জামালপুর সদর', 'জামালপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (325, 46, 5, 'serpur-sdr', 'শেরপুর সদর', 'শেরপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (326, 46, 5, 'nkla', 'নকলা', 'নকলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (327, 46, 5, 'nalitabaree', 'নালিতাবাড়ী', 'নালিতাবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (328, 46, 5, 'jhinaigatee', 'ঝিনাইগাতী', 'ঝিনাইগাতী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (329, 46, 5, 'sreebrdee', 'শ্রীবরদী', 'শ্রীবরদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (330, 47, 5, 'dhobauda', 'ধোবাউড়া', 'ধোবাউড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (331, 47, 5, 'haluyaghat', 'হালুয়াঘাট', 'হালুয়াঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (332, 47, 5, 'fulpur', 'ফুলপুর', 'ফুলপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (333, 47, 5, 'tarakanda', 'তারাকান্দা', 'তারাকান্দা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (334, 47, 5, 'goureepur', 'গৌরীপুর', 'গৌরীপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (335, 47, 5, 'muktagacha', 'মুক্তাগাছা', 'মুক্তাগাছা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (336, 47, 5, 'fulbareeya', 'ফুলবাড়ীয়া', 'ফুলবাড়ীয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (337, 47, 5, 'trisal', 'ত্রিশাল', 'ত্রিশাল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (338, 47, 5, 'eeswrgnj', 'ঈশ্বরগঞ্জ', 'ঈশ্বরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (339, 47, 5, 'nandail', 'নান্দাইল', 'নান্দাইল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (340, 47, 5, 'gfrgannoo', 'গফরগাঁও', 'গফরগাঁও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (341, 47, 5, 'valuka', 'ভালুকা', 'ভালুকা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (342, 47, 5, 'mymnsingh-sdr', 'ময়মনসিংহ সদর', 'ময়মনসিংহ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (343, 48, 5, 'duurgapur-2', 'দূর্গাপুর', 'দূর্গাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (344, 48, 5, 'klmakanda', 'কলমাকান্দা', 'কলমাকান্দা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (345, 48, 5, 'barhatta', 'বারহাট্টা', 'বারহাট্টা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (346, 48, 5, 'netrkona-sdr', 'নেত্রকোনা সদর', 'নেত্রকোনা সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (347, 48, 5, 'atpara', 'আটপাড়া', 'আটপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (348, 48, 5, 'kenduya', 'কেন্দুয়া', 'কেন্দুয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (349, 48, 5, 'khaliyajuree', 'খালিয়াজুরী', 'খালিয়াজুরী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (350, 48, 5, 'mdn', 'মদন', 'মদন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (351, 48, 5, 'mohngnj', 'মোহনগঞ্জ', 'মোহনগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (352, 48, 5, 'puurwdhla', 'পূর্বধলা', 'পূর্বধলা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (353, 49, 3, 'hosenpur', 'হোসেনপুর', 'হোসেনপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (354, 49, 3, 'kisorgnj-sdr', 'কিশোরগঞ্জ সদর', 'কিশোরগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (355, 49, 3, 'ktiyadee', 'কটিয়াদী', 'কটিয়াদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (356, 49, 3, 'pakundiya', 'পাকুন্দিয়া', 'পাকুন্দিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (357, 49, 3, 'krimgnj', 'করিমগঞ্জ', 'করিমগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (358, 49, 3, 'tarail', 'তারাইল', 'তারাইল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (359, 49, 3, 'oshtgram', 'অষ্টগ্রাম', 'অষ্টগ্রাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (360, 49, 3, 'itna', 'ইটনা', 'ইটনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (361, 49, 3, 'mithamin', 'মিঠামইন', 'মিঠামইন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (362, 49, 3, 'bajitpur', 'বাজিতপুর', 'বাজিতপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (363, 49, 3, 'niklee', 'নিকলী', ' নিকলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (364, 49, 3, 'voirb', 'ভৈরব', 'ভৈরব');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (365, 49, 3, 'kuliyarcr', 'কুলিয়ারচর', 'কুলিয়ারচর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (366, 50, 3, 'doultpur-3', 'দৌলতপুর', 'দৌলতপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (367, 50, 3, 'ghioor', 'ঘিওর', 'ঘিওর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (368, 50, 3, 'sibaly', 'শিবালয়', 'শিবালয়');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (369, 50, 3, 'manikgnj-sdr', 'মানিকগঞ্জ সদর', 'মানিকগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (370, 50, 3, 'hrirampur', 'হরিরামপুর', 'হরিরামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (371, 50, 3, 'singgair', 'সিংগাইর', 'সিংগাইর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (372, 50, 3, 'saturiya', 'সাটুরিয়া', 'সাটুরিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (373, 51, 3, 'sirajdikhan', 'সিরাজদিখান', 'সিরাজদিখান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (374, 51, 3, 'sreengr', 'শ্রীনগর', 'শ্রীনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (375, 51, 3, 'louhjng', 'লৌহজং', 'লৌহজং');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (376, 51, 3, 'tnggeebaree', 'টংগীবাড়ী', 'টংগীবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (377, 51, 3, 'gjariya', 'গজারিয়া', 'গজারিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (378, 51, 3, 'munseegnj-sdr', 'মুন্সীগঞ্জ সদর', 'মুন্সীগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (379, 52, 3, 'gajeepur-sdr', 'গাজীপুর সদর', 'গাজীপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (380, 52, 3, 'sreepur-2', 'শ্রীপুর', 'শ্রীপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (381, 52, 3, 'kapasiya', 'কাপাসিয়া', 'কাপাসিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (382, 52, 3, 'kalignj-3', 'কালিগঞ্জ', 'কালিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (383, 52, 3, 'kaliyakoir', 'কালিয়াকৈর', 'কালিয়াকৈর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (384, 52, 3, 'tngoee', 'টঙ্গী', 'টঙ্গী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (385, 53, 3, 'nrsingdee-sdr', 'নরসিংদী সদর', 'নরসিংদী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (386, 53, 3, 'plas', 'পলাশ', 'পলাশ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (387, 53, 3, 'sibpur', 'শিবপুর', 'শিবপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (388, 53, 3, 'belabo', 'বেলাবো', 'বেলাবো');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (389, 53, 3, 'mnohrdee', 'মনোহরদী', 'মনোহরদী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (390, 53, 3, 'raypura', 'রায়পুরা', 'রায়পুরা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (391, 56, 3, 'kasiyanee', 'কাশিয়ানী', 'কাশিয়ানী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (392, 56, 3, 'muksudpur', 'মুকসুদপুর', 'মুকসুদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (393, 56, 3, 'gopalgnj-sdr', 'গোপালগঞ্জ সদর', 'গোপালগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (394, 56, 3, 'kotalipara', 'কোটালিপাড়া', 'কোটালিপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (395, 56, 3, 'tunggeepara', 'টুংগীপাড়া', 'টুংগীপাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (396, 57, 3, 'sibcr', 'শিবচর', 'শিবচর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (397, 57, 3, 'madareepur-sdr', 'মাদারীপুর সদর', 'মাদারীপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (398, 57, 3, 'rajoir', 'রাজৈর', 'রাজৈর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (399, 57, 3, 'kalkinee', 'কালকিনী', 'কালকিনী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (400, 58, 3, 'sriytpur-sdr', 'শরিয়তপুর সদর', 'শরিয়তপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (401, 58, 3, 'jajira', 'জাজিরা', 'জাজিরা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (402, 58, 3, 'vedrgnj', 'ভেদরগঞ্জ', 'ভেদরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (403, 58, 3, 'nriya', 'নড়িয়া', 'নড়িয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (404, 58, 3, 'damudza', 'ডামুড্যা', 'ডামুড্যা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (405, 58, 3, 'gosairhat', 'গোসাইরহাট', 'গোসাইরহাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (406, 61, 8, 'dhrmpasa', 'ধর্মপাশা', 'ধর্মপাশা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (407, 61, 8, 'jamalgnj', 'জামালগঞ্জ', 'জামালগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (408, 61, 8, 'mdhzngr', 'মধ্যনগর', 'মধ্যনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (409, 61, 8, 'tahirpur', 'তাহিরপুর', 'তাহিরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (410, 61, 8, 'dirai', 'দিরাই', 'দিরাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (411, 61, 8, 'salla', 'শাল্লা', 'শাল্লা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (412, 61, 8, 'santignj', 'শান্তিগঞ্জ', 'শান্তিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (413, 61, 8, 'jgnnathpur', 'জগন্নাথপুর', 'জগন্নাথপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (414, 61, 8, 'biswmvrpur', 'বিশ্বম্ভরপুর', 'বিশ্বম্ভরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (415, 61, 8, 'sunamgnj-sdr', 'সুনামগঞ্জ সদর', 'সুনামগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (416, 61, 8, 'chatk', 'ছাতক', 'ছাতক');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (417, 61, 8, 'doyarabajar', 'দোয়ারাবাজার', 'দোয়ারাবাজার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (418, 62, 8, 'biswnath', 'বিশ্বনাথ', 'বিশ্বনাথ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (419, 62, 8, 'oosmaneengr', 'ওসমানীনগর', 'ওসমানীনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (420, 62, 8, 'kompaneegnj-2', 'কোম্পানীগঞ্জ', 'কোম্পানীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (421, 62, 8, 'goyainghat', 'গোয়াইনঘাট', 'গোয়াইনঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (422, 62, 8, 'jointapur', 'জৈন্তাপুর', 'জৈন্তাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (423, 62, 8, 'kanaighat', 'কানাইঘাট', 'কানাইঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (424, 62, 8, 'jkignj', 'জকিগঞ্জ', 'জকিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (425, 62, 8, 'biyanee-bajar', 'বিয়ানী বাজার', 'বিয়ানী বাজার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (426, 62, 8, 'golapgnj', 'গোলাপগঞ্জ', 'গোলাপগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (427, 62, 8, 'balagnj', 'বালাগঞ্জ', 'বালাগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (428, 62, 8, 'dkshin-surma', 'দক্ষিণ সুরমা', 'দক্ষিণ সুরমা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (429, 62, 8, 'fencugnj', 'ফেঞ্চুগঞ্জ', 'ফেঞ্চুগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (430, 62, 8, 'silet-sdr', 'সিলেট সদর', 'সিলেট সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (431, 63, 8, 'brlekha', 'বড়লেখা', 'বড়লেখা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (432, 63, 8, 'juree', 'জুড়ী', 'জুড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (433, 63, 8, 'kulaura', 'কুলাউড়া', 'কুলাউড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (434, 63, 8, 'moulveebajar-sdr', 'মৌলভীবাজার সদর', 'মৌলভীবাজার সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (435, 63, 8, 'rajngr', 'রাজনগর', 'রাজনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (436, 63, 8, 'kmlgnj', 'কমলগঞ্জ', 'কমলগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (437, 63, 8, 'sreemngol', 'শ্রীমঙ্গল', 'শ্রীমঙ্গল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (438, 64, 8, 'bahubl', 'বাহুবল', 'বাহুবল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (439, 64, 8, 'nbeegnj', 'নবীগঞ্জ', 'নবীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (440, 64, 8, 'ajmirignj', 'আজমিরিগঞ্জ', 'আজমিরিগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (441, 64, 8, 'baniyacng', 'বানিয়াচং', 'বানিয়াচং');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (442, 64, 8, 'hbignj-sdr', 'হবিগঞ্জ সদর', 'হবিগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (443, 64, 8, 'lakhai', 'লাখাই', 'লাখাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (444, 64, 8, 'sayestagnj', 'শায়েস্তাগঞ্জ', 'শায়েস্তাগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (445, 64, 8, 'cunarughat', 'চুনারুঘাট', 'চুনারুঘাট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (446, 64, 8, 'madhbpur', 'মাধবপুর', 'মাধবপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (447, 17, 2, 'daudkandi', 'দাউদকান্দি', 'দাউদকান্দি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (448, 17, 2, 'titas', 'তিতাস', 'তিতাস');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (449, 17, 2, 'homna', 'হোমনা', 'হোমনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (450, 17, 2, 'meghna', 'মেঘনা', 'মেঘনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (451, 17, 2, 'muradngr', 'মুরাদনগর', 'মুরাদনগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (452, 17, 2, 'debidwar', 'দেবিদ্বার', 'দেবিদ্বার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (453, 17, 2, 'brakshmn-para', 'ব্রাক্ষ্মণ পাড়া', 'ব্রাক্ষ্মণ পাড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (454, 17, 2, 'buricng', 'বুড়িচং', 'বুড়িচং');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (455, 17, 2, 'candina', 'চান্দিনা', 'চান্দিনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (456, 17, 2, 'brura', 'বরুড়া', 'বরুড়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (457, 17, 2, 'laksam', 'লাকসাম', 'লাকসাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (458, 17, 2, 'mnohrgnj', 'মনোহরগঞ্জ', 'মনোহরগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (459, 17, 2, 'lalmai', 'লালমাই', 'লালমাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (460, 17, 2, 'nangolkot', 'নাঙ্গলকোট', 'নাঙ্গলকোট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (461, 17, 2, 'kumilla-sdr-dkshin', 'কুমিল্লা সদর দক্ষিণ', 'কুমিল্লা সদর দক্ষিণ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (462, 17, 2, 'couddgram', 'চৌদ্দগ্রাম', 'চৌদ্দগ্রাম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (463, 17, 2, 'kumilla-adrs-sdr', 'কুমিল্লা আদর্শ সদর', 'কুমিল্লা আদর্শ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (464, 9, 2, 'ckriya', 'চকরিয়া', 'চকরিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (465, 9, 2, 'pekuya', 'পেকুয়া', 'পেকুয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (466, 9, 2, 'kutubdiya', 'কুতুবদিয়া', 'কুতুবদিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (467, 9, 2, 'mheskhalee', 'মহেশখালী', 'মহেশখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (468, 9, 2, 'kksbajar-sdr', 'কক্সবাজার সদর', 'কক্সবাজার সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (469, 9, 2, 'eedgannoo', 'ঈদগাঁও', 'ঈদগাঁও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (470, 9, 2, 'ramu', 'রামু', 'রামু');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (471, 9, 2, 'teknaf', 'টেকনাফ', 'টেকনাফ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (472, 9, 2, 'ukhiya', 'উখিয়া', 'উখিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (473, 10, 2, 'dighinala', 'দিঘিনালা', 'দিঘিনালা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (474, 10, 2, 'guimara', 'গুইমারা', 'গুইমারা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (475, 10, 2, 'khagrachri-sdr', 'খাগড়াছড়ি সদর', 'খাগড়াছড়ি সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (476, 10, 2, 'lksheechri', 'লক্ষীছড়ি', 'লক্ষীছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (477, 10, 2, 'mhalchri', 'মহালছড়ি', 'মহালছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (478, 10, 2, 'manikchri', 'মানিকছড়ি', 'মানিকছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (479, 10, 2, 'matirangga', 'মাটিরাংগা', 'মাটিরাংগা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (480, 10, 2, 'panchri', 'পানছড়ি', 'পানছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (481, 10, 2, 'ramgr', 'রামগড়', 'রামগড়');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (482, 11, 2, 'baghaichri', 'বাঘাইছড়ি', 'বাঘাইছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (483, 11, 2, 'brkl', 'বরকল', 'বরকল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (484, 11, 2, 'kaukhalee-2', 'কাউখালী', 'কাউখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (485, 11, 2, 'bilaichri', 'বিলাইছড়ি', 'বিলাইছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (486, 11, 2, 'kaptai', 'কাপ্তাই', 'কাপ্তাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (487, 11, 2, 'jurachri', 'জুরাছড়ি', 'জুরাছড়ি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (488, 11, 2, 'lnggdu', 'লংগদু', 'লংগদু');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (489, 11, 2, 'naniyarcr', 'নানিয়ারচর', 'নানিয়ারচর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (490, 11, 2, 'rajsthalee', 'রাজস্থালী', 'রাজস্থালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (491, 11, 2, 'rangoamati-sdr', 'রাঙ্গামাটি সদর', 'রাঙ্গামাটি সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (492, 59, 3, 'goyalnd', 'গোয়ালন্দ', 'গোয়ালন্দ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (493, 59, 3, 'rajbaree-sdr', 'রাজবাড়ী সদর', 'রাজবাড়ী সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (494, 59, 3, 'baliyakandi', 'বালিয়াকান্দি', 'বালিয়াকান্দি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (495, 59, 3, 'kalukhalee', 'কালুখালী', 'কালুখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (496, 59, 3, 'pangsa', 'পাংশা', 'পাংশা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (497, 60, 3, 'alphadangoa', 'আলফাডাঙ্গা', 'আলফাডাঙ্গা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (498, 60, 3, 'boyalmaree', 'বোয়ালমারী', 'বোয়ালমারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (499, 60, 3, 'mdhukhalee', 'মধুখালী', 'মধুখালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (500, 60, 3, 'ngrkanda', 'নগরকান্দা', 'নগরকান্দা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (501, 60, 3, 'saltha', 'সালথা', 'সালথা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (502, 60, 3, 'fridpur-sdr', 'ফরিদপুর সদর', 'ফরিদপুর সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (503, 60, 3, 'vangga', 'ভাংগা', 'ভাংগা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (504, 60, 3, 'crvdrasn', 'চরভদ্রাসন', 'চরভদ্রাসন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (505, 60, 3, 'sdrpur', 'সদরপুর', 'সদরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (506, 54, 3, 'ruupgnj', 'রূপগঞ্জ', 'রূপগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (507, 54, 3, 'araihajar', 'আড়াইহাজার', 'আড়াইহাজার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (508, 54, 3, 'sonargannoo', 'সোনারগাঁও', 'সোনারগাঁও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (509, 54, 3, 'narayngnj-sdr', 'নারায়ণগঞ্জ সদর', 'নারায়ণগঞ্জ সদর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (510, 54, 3, 'bndr', 'বন্দর', 'বন্দর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (511, 55, 3, 'dohar', 'দোহার', 'দোহার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (512, 55, 3, 'nbabgnj-2', 'নবাবগঞ্জ', 'নবাবগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (513, 55, 3, 'keraneegnj', 'কেরানীগঞ্জ', 'কেরানীগঞ্জ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (514, 55, 3, 'savar', 'সাভার', 'সাভার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (515, 55, 3, 'dhamrai', 'ধামরাই', 'ধামরাই');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (516, 55, 3, 'adabr', 'আদাবর', 'আদাবর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (517, 55, 3, 'badda', 'বাড্ডা', 'বাড্ডা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (518, 55, 3, 'bngsal', 'বংশাল', 'বংশাল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (519, 55, 3, 'biman-bndr', 'বিমান বন্দর', 'বিমান বন্দর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (520, 55, 3, 'bnanee', 'বনানী', 'বনানী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (521, 55, 3, 'kzantnment', 'ক্যান্টনমেন্ট', 'ক্যান্টনমেন্ট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (522, 55, 3, 'ckbajar', 'চকবাজার', 'চকবাজার');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (523, 55, 3, 'dkshinkhan', 'দক্ষিণখান', 'দক্ষিণখান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (524, 55, 3, 'demra', 'ডেমরা', 'ডেমরা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (525, 55, 3, 'dhanmndi', 'ধানমন্ডি', 'ধানমন্ডি');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (526, 55, 3, 'vashantek', 'ভাষানটেক', 'ভাষানটেক');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (527, 55, 3, 'vatara', 'ভাটারা', 'ভাটারা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (528, 55, 3, 'gendariya', 'গেন্ডারিয়া', 'গেন্ডারিয়া');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (529, 55, 3, 'gulsan', 'গুলশান', 'গুলশান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (530, 55, 3, 'hatirjhil', 'হাতিরঝিল', 'হাতিরঝিল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (531, 55, 3, 'hajareebag', 'হাজারীবাগ', 'হাজারীবাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (532, 55, 3, 'zatrabaree', 'যাত্রাবাড়ী', 'যাত্রাবাড়ী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (533, 55, 3, 'kafrul', 'কাফরুল', 'কাফরুল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (534, 55, 3, 'kdmtlee', 'কদমতলী', 'কদমতলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (535, 55, 3, 'kamrangoeer-cr', 'কামরাঙ্গীর চর', 'কামরাঙ্গীর চর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (536, 55, 3, 'khilgannoo', 'খিলগাঁও', 'খিলগাঁও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (537, 55, 3, 'khilkshet', 'খিলক্ষেত', 'খিলক্ষেত');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (538, 55, 3, 'kotyalee-2', 'কোতয়ালী', 'কোতয়ালী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (539, 55, 3, 'lalbag', 'লালবাগ', 'লালবাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (540, 55, 3, 'mirpur-2', 'মিরপুর', 'মিরপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (541, 55, 3, 'mohammdpur-2', 'মোহাম্মদপুর', 'মোহাম্মদপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (542, 55, 3, 'mtijhil', 'মতিঝিল', 'মতিঝিল');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (543, 55, 3, 'mugda', 'মুগদা', 'মুগদা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (544, 55, 3, 'niu-market', 'নিউ মার্কেট', 'নিউ মার্কেট');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (545, 55, 3, 'pllbee', 'পল্লবী', 'পল্লবী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (546, 55, 3, 'pltn', 'পল্টন', 'পল্টন');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (547, 55, 3, 'rmna', 'রমনা', 'রমনা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (548, 55, 3, 'rampura', 'রামপুরা', 'রামপুরা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (549, 55, 3, 'sbujbag', 'সবুজবাগ', 'সবুজবাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (550, 55, 3, 'sahjahanpur', 'শাহজাহানপুর', 'শাহজাহানপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (551, 55, 3, 'sah-alee', 'শাহ্‌ আলী', 'শাহ্‌ আলী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (552, 55, 3, 'sahbag', 'শাহবাগ', 'শাহবাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (553, 55, 3, 'szampur', 'শ্যামপুর', 'শ্যামপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (554, 55, 3, 'sere-bangla-ngr', 'শেরে বাংলা নগর', 'শেরে বাংলা নগর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (555, 55, 3, 'sutrapur', 'সুত্রাপুর', 'সুত্রাপুর');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (556, 55, 3, 'tejgannoo', 'তেজগাঁও', 'তেজগাঁও');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (557, 55, 3, 'tejgannoo-silp-elaka', 'তেজগাঁও শিল্প এলাকা', 'তেজগাঁও শিল্প এলাকা');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (558, 55, 3, 'turag', 'তুরাগ', 'তুরাগ');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (559, 55, 3, 'uttra-pscim', 'উত্তরা পশ্চিম', 'উত্তরা পশ্চিম');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (560, 55, 3, 'uttra-puurw', 'উত্তরা পূর্ব', 'উত্তরা পূর্ব');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (561, 55, 3, 'uttr-khan', 'উত্তর খান', 'উত্তর খান');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (562, 55, 3, 'waree', 'ওয়ারী', 'ওয়ারী');
INSERT INTO upazilas (id, district_id, division_id, slug, name, name_en) VALUES (563, 55, 3, 'klabagan', 'কলাবাগান', 'কলাবাগান');
